<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - Login Test</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>Login Test</h1>
<p>
  Test duration: 17.032s
</p>




  <table class="resultsTable" width="100%">
    <tr><th colspan="3" class="header skipped">Skipped Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.e2e.testcases.LoginTest</td>
      </tr>
            
<tr>
  <td class="method">
                  logintest
      </td>
  <td class="duration">
    0.009s
  </td>
  <td class="result">
                                 	<i>Reason: </i>
      	<span class="dependency">Skipping Test case Iteration as runmode is set to No</span>
          
          <i>Method arguments: </i><span class="arguments">{URL=http://www.way2automation.com/angularjs-protractor/banking/#/login, RunMode=N, TestData=login1, Iteration=1.0, Browser=Firefox}, public void com.e2e.testcases.LoginTest.logintest(java.util.Hashtable,java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException</span><br />
    
        

      </td>
</tr>
      </table>

  <table class="resultsTable">
    <tr><th colspan="3" class="header passed">Passed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.e2e.testcases.LoginTest</td>
      </tr>
            
<tr>
  <td class="method">
                  logintest
      </td>
  <td class="duration">
    10.543s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">{URL=http://www.way2automation.com/angularjs-protractor/banking/#/login, RunMode=Y, TestData=login2, Iteration=2.0, Browser=Chrome}, public void com.e2e.testcases.LoginTest.logintest(java.util.Hashtable,java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException</span><br />
    
            <div class="testOutput">
                        Execution finished for Login Test Case
                  </div>
    

      </td>
</tr>
      </table>
  
</body>
</html>
